# Generated by Django 5.0.6 on 2024-08-04 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='retialer',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='category',
            field=models.CharField(choices=[('Food', 'Food'), ('Transportation', 'Transportation'), ('Clothing', 'Clothing'), ('Utilities', 'Utilities'), ('Vacation', 'Vacation'), ('Others', 'Others')], max_length=50),
        ),
    ]
