# Generated by Django 5.0.6 on 2024-08-06 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_transactions_retialer_alter_transactions_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactions',
            old_name='retialer',
            new_name='retailer',
        ),
    ]
