# Generated by Django 5.0.6 on 2024-08-06 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_retialer_transactions_retailer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='date',
            field=models.DateField(),
        ),
    ]
