# Generated by Django 5.1 on 2024-08-29 00:26

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.CharField(max_length=100)),
                ('organization', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('profile', models.CharField(max_length=100)),
                ('transaction_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date', models.DateField(default=datetime.date(2024, 8, 29))),
                ('time', models.DateTimeField(default=datetime.datetime.now)),
                ('category', models.CharField(blank=True, choices=[('Food', 'Food'), ('Transportation', 'Transportation'), ('Clothing', 'Clothing'), ('Utilities', 'Utilities'), ('Vacation', 'Vacation'), ('Others', 'Others')], max_length=50)),
                ('retailer', models.CharField(blank=True, max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.IntegerField()),
                ('balance', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('cash_flow', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Food', 'Food'), ('Transportation', 'Transportation'), ('Clothing', 'Clothing'), ('Utilities', 'Utilities'), ('Vacation', 'Vacation'), ('Others', 'Others')], max_length=50)),
                ('set_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.profile')),
            ],
        ),
    ]
