# Generated by Django 5.1 on 2024-08-30 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_profile_clothing_budget_profile_food_budget_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Budget',
        ),
    ]
