# Generated by Django 5.1 on 2024-08-29 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='profile',
            field=models.CharField(max_length=100),
        ),
    ]
