# Generated by Django 5.1 on 2024-09-07 19:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_delete_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='date',
            field=models.DateField(default=datetime.date(2024, 9, 7)),
        ),
    ]
