# Generated by Django 5.1 on 2024-10-10 20:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_transactions_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='category',
            field=models.CharField(blank=True, choices=[('Food', 'Food'), ('Transportation', 'Transportation'), ('Clothing', 'Clothing'), ('Utilities', 'Utilities'), ('Groceries', 'Groceries'), ('Others', 'Others')], max_length=50),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='date',
            field=models.DateField(default=datetime.date(2024, 10, 10)),
        ),
    ]
