# Generated by Django 5.1 on 2024-10-13 17:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_csvfiles_alter_transactions_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvfiles',
            name='year',
            field=models.IntegerField(default=2024),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='date',
            field=models.DateField(default=datetime.date(2024, 10, 13)),
        ),
    ]
